version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstoredb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bookstoreapp:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=bookstoredb;Username=postgres;Password=postgres
    depends_on:
      - postgres

volumes:
  pgdata:
