apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bookstore
data:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=bookstoredb;Username=postgres;Password=postgres;SslMode=Disable"
  ASPNETCORE_ENVIRONMENT: "Production"
